### ISSUE TITLE
composer installが失敗します

### ISSUE THREAD

**Issue by jidaikobo-shibata** [laravel-jp-reference/chapter2#2]
#先ほど間違ったスレッドに投稿してしまいました。すみません。

可能であれば、以下、ご教示願います。

『Laravel リファレンス』を購入し、指示された手順に従ってchapter2をcloneしましたところ、
`composer install`
で
`Your configuration does not allow connections to...`
というエラーが出て、うまくいきませんでした。

composer.jsonに
`"secure-http": false,`
を足すと良い、という記述を見つけ、試してみましたが、
`  - Installing symfony/process (v2.7.7): Warning: Accessing toran.local over http which is an insecure protocol.
Downloading (failed)...`
と少しエラーは変わるのですが、failedが連続します。

普通の
`laravel new project`
は成功するみたいです。

環境は

- PHP 5.6.30
- Composer version 1.4.2

という感じです。

なにか手はありますでしょうか？

**Comment by HiroKws** [comment]
書籍は２年以上前の環境を元にして著述しました。その後、Compsoerの仕様が変更されたため、動かない状況があります。

まず、プロジェクトルートに存在する、composer.jsonファイルを削除し、お試しください。

**Comment by jidaikobo-shibata** [comment]
お返事をありがとうございます。また、お手数をすみません。

すこし古い本であることは認識しておりますので、そのまま使えない場合は、その旨了解します。

でも、composer.jsonファイルを削除して、`composer install`したら、ただのエラーになるのではと思ったのですが、案の定、`Composer could not find a composer.json file in...`となります。

プロジェクトルートというのは、cloneしたディレクトリのことで理解が間違っていますでしょうか？

**Comment by HiroKws** [comment]
ああ、すいません。composer.jsonではなく、composer.lockファイルです。

**Comment by HiroKws** [comment]
それでも、エラーが発生する場合は、composer update --no-scriptsをお試しください。現在、同じ動作環境が作成できないため、php7で試していますが、これでインストールは完了できるようです。

**Comment by jidaikobo-shibata** [comment]
ですよね ;)

すると、今度はこんな感じでした。

```
> php artisan clear-compiled
PHP Warning:  require(/path/to/../vendor/autoload.php): failed to open stream: No such file or directory in /path/to/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/path/to/../vendor/autoload.php' (include_path='.:') in /path/to/autoload.php on line 17

Warning: require(/path/to/../vendor/autoload.php): failed to open stream: No such file or directory in /path/to/autoload.php on line 17

Fatal error: require(): Failed opening required '/path/to/../vendor/autoload.php' (include_path='.:') in /path/to/autoload.php on line 17
Script php artisan clear-compiled handling the pre-update-cmd event returned with error code 255
```

autoload.phpを見失うみたいです。

**Comment by jidaikobo-shibata** [comment]
あ、すみません。入れ違いました。

でも、`composer update --no-scripts`が、どうやら行けそうな雰囲気です！

**Comment by jidaikobo-shibata** [comment]
Installingが、堰を切ったように流れてきました！

おかげさまで本を読み進められます。

ご対応、ありがとうございました。

**Comment by HiroKws** [comment]
前で別件で問い合わせがあったときに確認したらupdateではインストールできずに、installでしか初期のインストールはできなかったのに、現在はupdateでも、installでも、インストールできる状況に戻っているようです。本当に、Composerは動作がちょくちょく変更されます。

readmeに注釈を追加しておきます。
